language: node_js
node_js:
  - "stable"

script:
  - yarn install
  - npm run build

deploy: 
  provider: surge
  skip_cleanup: true
  domain: demoSpaceX-WebApp.surge.sh/
  project: ./build/


on:
  branch: master